ACTION_INTENT = "Intent"
ACTION_EVENT = "Event"
ACTION_STATUS = "Status"

DEVICE_APP = "app"
DEVICE_DOOR = "door"
DEVICE_DISTANCE = "distance"

SUBSCRIBE_TO_APP = DEVICE_APP + "/+/+"
SUBSCRIBE_TO_DOOR = DEVICE_DOOR + "/+/+"
SUBSCRIBE_TO_DISTANCE = DEVICE_DISTANCE + "/+/+"

PUBLISH_TO_APP = DEVICE_APP + "/+/"
PUBLISH_TO_DOOR = DEVICE_DOOR + "/+/"
PUBLISH_TO_DISTANCE = DEVICE_DISTANCE + "/+/"
